# Generated by Django 5.2.11 on 2026-02-07 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=108, verbose_name='书名')),
                ('author', models.CharField(max_length=88, verbose_name='作者')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='图书封面')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可借')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅时间')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='借阅人')),
            ],
            options={
                'verbose_name': '借阅管理',
                'verbose_name_plural': '借阅管理',
            },
        ),
    ]
